# Generated by Django 4.1.3 on 2022-11-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
